package by.htp.ex01.controller.command;

public enum CommandName {
	LOGINATION, REGISTRATION, SAVENEWUSER, GOTOINDEXPAGE, GOTOMAINPAGE,
	LOGOUT, GOTOCONTENTPAGE, EDITNEWS, SAVEEDITNEWS, DELETENEWS,
	CHANGELANG
}
